### ISSUE TITLE
Game Engine

### ISSUE THREAD

**Issue by quattro004** [IntelliTect/Hackathon2022Homestead#3]
Maintains game state

**Comment by PandaMagnus** [comment]
1. Turn starts with drawing a card from either the Deck (random) or the discard pile if it contains cards. 
2. The card is put into the player’s hand 
3. The player then selects an action (playable actions are highlighted on the board) 
   a. The player is forced to play a card into a blank spot on the board if they have that card.  
   b. Play a card against another player 
   c. The player is forced to discard if they have more than 4 cards 
   d. If all mandatory plays have been made, then the turn can be over 
   e. Turn ends when the player either chooses not to take an action or discards 
4. Player wins when they have all 8 cards on the board

**Comment by PandaMagnus** [comment]
Possible starting functions:

Assess State / Actions

Draw a card
   From draw pile
   From discard pile
   List of actions (below are possibilities)
      Add to hand (if not disaster, if not first homestead card)
      Immediately play (first homestead card, disaster)
Discard a card
Play a card
   Build homestead
   Give card to player?
